= C++ Compile
:copyright: Copyright 2017-2018 Rene Rivera
:author: Rene Rivera
:email: grafikrobot@gmail.com
:revnumber: PxxxR0
:revdate: {docdate}
:revremark: Initial
:version-label!: 
:reproducible:
:nofooter:
:sectanchors:
:sectnums:
:source-highlighter: highlightjs
:source-language: c++
:toc: left
:toclevels: 3
:caution-caption: ⚑
:important-caption: ‼
:note-caption: ℹ
:tip-caption: ☀
:warning-caption: ⚠

ifdef::backend-html5[]
++++
<style>
.admonitionblock .icon .title {
    font-size: 2.5em;
    text-shadow: 1px 1px 2px rgba(0, 0, 0, .5);
}
.caution .icon .title {
    color: rgba(192, 51, 0, 1);
}
.important .icon .title {
    color: rgba(192, 0, 0, 1);
}
.note .icon .title {
    color: rgba(26, 64, 128, 1);
}
.tip .icon .title {
    color: rgba(255, 192, 0, 1);
}
.warning .icon .title {
    color: rgba(192, 102, 0, 1);
}
</style>
++++
endif::[]

[horizontal]
Document number:: {revnumber}
Date:: {revdate}
Reply-to:: {author}, {email}
Audience:: Study Group 15, Library Evolution

== Introduction

This proposes the addition of an interface for transforming C++ source into
usable binary images. As such it aims to provide a common definition of
existing compiler frontend tool options for generating programs and libraries
for translation units.

=== Background and Motivation

This proposal is based on the notion that it should be possible for a C++
user, both beginner and advanced, to easily transform their source to
immediately executable form in a consistent method across compilers.

One key aspect of this proposal is to make it possible for future C++
educators, and book authors, to provide complete usage examples that work for
any particular tool they and their audience use. While this proposal does not
prescribe a particular executable tool, it is trivial to write minimal tool
that passes arguments directly to these interfaces.

It is also the intent for this proposal to be an initial step in the road
towards standardizing the tooling around C++. With the goal of having a
global and consistent tooling ecosystem to facilitate the introduction into
C++ for anyone and to ease the interoperability of future tooling.

=== Impact On the Standard

This proposal is a library extension and specification. As such it does not
proscribe changes to any standard classes or functions. It adds one function
and some definitions to a new header file, `<compile>`.

=== Design Goals

The design herein is driven primarily by the following, in approximate
order of importance:

* Mirror the `main` entry point to make a frontend program trivial.
* Minimize variability in arguments and options.
* Use common practice option names for familiarity.
* Do not attempt to specify all possible options as that's not technically
possible.
* Specify how, and if, options are compatible with others.

=== Design Decisions

==== Exceptions

So as to reduce error handling cases for callers of `compile`, i.e. `main`,
there are no exceptions allowed from calls to `compile`. This has the effect
of removing the need for exception handling at the caller as any error
situations are indicated by the simpler return value which can be directly
mapped to the return value of `main`.

==== Vendor Arguments

Recognizing that specifying a complete set of argument options is not possible
we need to provide for a mechanism to pass vendor specific arguments for
compilation; but at the same time we want to ensure that defined arguments
are not ignored in favor of vendor only arguments. Hence we specify this
implementation rule:

When a defined argument option exists a vendor specific argument is *not*
allowed as an acceptable argument option.

For instance::
??

==== Extension Arguments

Given the faster rate at which compilers change with respect to the C++
standard we need to allow for specification of arguments as quickly as
possible to facilitate support in tooling.

For instance::
A vendor release a new version of their compiler to support a new CPU.
This new CPU is not compatible with an existing CPU and hence packages must
be recompiled for it. But the next possibility scheduled committee meeting
that could approve adding that new CPU option is months later.

== Technical Specification

=== Header `<compile>` Synopsis

----
namespace std
{
  int compile(int, char * *) noexcept;
}
----

=== Specification

----
int compile(int argument_count, char * * arguments) noexcept;
----

[horizontal]

Requires:: `argument_count > 0`, where `arguments[0]` is the name of the
program executable. And `arguments[1..argument_count)` are either either
options or names of source files.

Effect:: Executes the compilation according to the given `arguments`.

Returns:: zero (`0`) for success, non-zero (`!= 0`) for an error.

==== Arguments

The `arguments` specify the set of options and source translation units to
compile.

===== Core Options

include::../src/opt_core.cpp[leveloffset=+5,tag=std_cpp]

== Prior Art

== Acknowledgements

