= C++ Compile
:copyright: Copyright 2017-2018 Rene Rivera
:author: Rene Rivera
:email: grafikrobot@gmail.com
:docnumber: Dxxxx
:revnumber: {docnumber}R0
:revdate: {docdate}
:revremark: Initial
:version-label!: 
:reproducible:
:nofooter:
:sectanchors:
:sectnums:
:source-highlighter: highlightjs
:source-language: c++
:toc: left
:toclevels: 3
:caution-caption: ⚑
:important-caption: ‼
:note-caption: ℹ
:tip-caption: ☀
:warning-caption: ⚠
:CPP: C++
:PP: ++
:P: +

ifdef::backend-html5[]
++++
<style>
include::std.css[]
</style>
++++
endif::[]

[horizontal]
Document number:: ISO/IEC/JTC1/SC22/WG21/{revnumber}
Date:: {revdate}
Reply-to:: {author}, {email}
Audience:: Study Group 15, Library Evolution

== Introduction

This proposes to add an interface for transforming {CPP} source into
usable executable programs. As such it aims to provide a common definition of
compiler frontend tool options for transforming source code to translation units
and linking those into executable programs.

=== Background and Motivation

This proposal is based on the notion that it should be possible for a {CPP}
user, both beginner and advanced, to easily transform their source to
immediately executable form in a consistent method across compilers.

One key aspect of this proposal is to make it possible for future {CPP}
educators, and book authors, to provide complete usage examples that work for
any particular tool they and their audience use. While this proposal does not
prescribe a particular executable tool, it is trivial to write minimal tool
that passes arguments directly to these interfaces.

It is also the intent for this proposal to be an initial step in the road
towards standardizing the tooling around {CPP}. With the goal of having a
global and consistent tooling ecosystem to facilitate the introduction into
{CPP} for anyone and to ease the interoperability of future tooling like
package and dependency managers by having a single common set of options
to base solutions on.

Additionally this facility would also support runtime compilation, for example
for runtime generated source, and other compilation models where the particular
execution platform is not know ahead of time.

=== Impact On the Standard

This proposal is a library extension and specification. As such it does not
proscribe changes to any standard classes or functions. It adds one function
in a new header file, `<compile>`.

=== Design Goals

The design herein is driven primarily by the following, in approximate
order of importance:

* Mirror the `main` entry point to make a frontend program trivial.
* Minimize variability in arguments and options.
* Use common practice option names for familiarity.
* Do not attempt to specify all possible options as that's not technically
  possible.
* Specify how, and if, options are compatible with others.

=== Design Decisions

==== Exceptions

So as to reduce error handling cases for callers of `compile`, i.e. `main`,
there are no exceptions allowed from calls to `compile`. This has the effect
of removing the need for exception handling at the caller as any error
situations are indicated by the simpler return value which can be directly
mapped to the return value of `main`.

==== Argument Exclusivity

Recognizing that specifying a complete set of argument options is not possible
we need to provide for a mechanism to pass vendor specific arguments for
compilation; but at the same time we want to ensure that defined arguments
are not ignored in favor of vendor only arguments. Hence we specify this
implementation rule:

****
When a defined argument option exists an equivalent vendor specific argument
is *not* allowed as an acceptable argument option.
****

For instance::
We specify the `{PP}address_model` core option. It would not be allowed for
a vendor to specify an `{PP}v:xyz:m64` (to specify 64 bit address model) option
as that would overlap with the core option.

==== Vendor Arguments

Given the faster rate at which compilers change with respect to the {CPP}
standard we need to allow for specification of arguments as quickly as
possible to facilitate support in tooling.

For instance::
A vendor releases a new version of their compiler to support a new CPU.
This new CPU is not compatible with an existing CPU and hence packages must
be recompiled for it. But the next scheduled committee meeting that could
approve adding that new CPU option is months later.

Hence we propose the use _Standing Documents_ for specifying the vendor
specific options and for the highly volatile option values as needed. Such
that SG15 could meet and approve changes to those _Standing Documents_
as needed.

==== `{P}` Option Prefix

Like choosing names for programming language constructs, choosing a prefix
for the option arguments is a contentious decision. For this we chose to
use `{P}` as the prefix, and hence `{PP}` for the long form, for these reasons:

* It's not used in current compiler tooling and hence avoids confusion with
  existing options.
* It doesn't conflict with operating system specific path specifications.
* Is a non-alphanumeric ASCII glyph.
* Not frequently used as the first character of file names.
* And finally, it harkens to {CPP} itself.

==== Use Cases

This facility is designed to facilitate primarily these groups of users:
teachers (and their students), and tool creators. For teachers this feature
would improve, by simplifying, the teaching materials presented to students.

For instance::
This is the first code example from a popular {CPP} programming book:
+
[quote, Bjarne Stroustrup, The {CPP} Programming Language Third Edition]
____
For example:
[source]
----
#include<iostream>

int main()
{
  std::cout << "Hello, new world!\n";
}
----
____
+
Which is shortly followed by this explanation:
+
____
The language used in this book is "`pure {CPP}`" as defined in the {CPP} standard
[{CPP},1998]. Therefore, the example ought to run on every {CPP} implementation.
The major program fragments in this book were tried using several {CPP}
implementations.
____
+
But how to run and compile examples is not describe in the entirety of the
book for good reasons. As it would take a whole chapter onto itself just
to skim at that subject. With this proposal it would at least be possible
to give a short explanation of what a compiler invocation would look like.
The above example could be followed by:
+
____
You can compile the example with this command, substituting a compiler
program of your choice:
----
> cpp hello.cpp ++output=hello.exe
----
And run it by invoking the resulting program:
----
> hello.exe
Hello, new world!
----
____

For tool creators the uses vary depending on the tools in question. They could
be a build system, like `b2` (aka Boost.Build) that has complicated toolset
definition files that translate portable build descriptions to specific
tool invocations.

For instance::
In `b2` one would indicate include search paths by adding
`<include>my/include` to the specification of the build definition. It will
then translate that to a compile invocation depending on the tool:
`cl.exe /I "my/include"`, `cc -Imy/include`, `bcc32.exe -I"my/include"`,
`clang -I"my/include"`, `gcc -I"my/include"`, `cl.exe /I"my/include"`, and so
on. This is obviously a very simple example and the options get less uniform
across compilers the more "esoteric" the options are. And the build system
needs lots of human programed knowledge to create these mappings. Instead
with this proposal the mapping would be universal and only non-core options
and the tool executable would need special treatment.

Publishing libraries, with or without source, also poses a problem for those
doing the publishing. As part of publishing your library will have specific
options it needs your program to compile with to make use of the library. This
can involve rather complex distributions to account for the varied compilers
end users have. And many times this involves publishing many different files
for each possible configuration and compiler you support.

For instance::
One common method of doing that is to use pkg-config. You might end up with
this kind of file for GCC:
+
----
Name: libpng
Description: Loads and saves PNG files
Version: 1.2.8
Libs: -L${libdir} -lpng12 -lz
Cflags: -I${includedir}/libpng12
----
+
And another for MSVC:
+
----
Name: libpng
Description: Loads and saves PNG files
Version: 1.2.8
Libs: /LIBPATH:${libdir} png12.lib z.lib
Cflags: /I${includedir}/libpng12
----
+
With this proposal it would be possible to only include one such file
regardless of compiler used:
+
----
Name: libpng
Description: Loads and saves PNG files
Version: 1.2.8
Libs: ++library_path=${libdir} +lpng12 +lz
Cflags: +I${includedir}/libpng12
----

The uses are not limited to the above two groups of users though. This
facility also opens the door for some users that need to process
generated source into executable form.

For instance::
One can have a system that uses database schema definitions to generate {CPP}
source code to implement that schema, and related queries, in an optimal
form backed by a custom {CPP} database engine. This would let one do that
operation in a much simpler and direct method.

=== About Linking

When considering this extension the question comes up about the definition of
generating compiled source files and linking them into a program. The key issue
is that there is the claim that there is no normative text in the standard
that defines the process of separate compilation and linking.

My research, with regards to reading the standard text, is that even though
the standard does tread carefully to avoid specifics about the interaction
of external linkage, compiling, and the resulting program; There is a definite
understood specification that one "translates" source code units into separate
"blobs" that are then "linked" into the final runnable program. Specifically
section 6.5 ([basic.link]) defines this process with:

****
A _program_ consists of one or more _translation units_ (Clause 5) linked
together. A translation unit consists of a sequence of declarations.
****

This proposal doesn't claim to define the compilation and linkage any further
than is currently defined. The options mandated herein do not specify any
particular process or mechanisms past the existing specification of program
and linkage. This proposal does not:

1.Proscribe any particular storage mechanism for source code, translated
  source code, nor a program.
2.Proscribe any particular format for translated source code nor program.

And hence the specifics of what the results of compiling the translation units
into linkable outputs and linking those outputs into an executable program
is entirely implementation defined.

=== Link Compatibility

This proposal defines a _link compatibility_ for options to make it clear what
compiled translation units are compatible with each other. This information
facilitates various use cases:

* It makes it possible for build systems to detect and respond to the
  compatibility. To either notify the user of the problem, or to create
  variations that are compatible with your request.
* It makes it possible for package managers that support pre-compiled binary
  libraries to detect if the available packages are usable with your program.
  And possibly adjust to find the particular binary variation that will work
  for your case.

== Technical Specification

NOTE: This is a *_very rough_* draft of a specification. As such it will
contain errors and not be written in the most precise manner.

=== Header `<compile>` Synopsis

----
namespace std
{
  int compile(int, char * *) noexcept;
}
----

=== Specification

----
int compile(int argument_count, char * * arguments) noexcept;
----

[horizontal]

Requires:: `argument_count > 0`, where `arguments[0]` is the name of the
program executable. And `arguments[1..argument_count)` are either either
options or names of source files.

Effect:: Executes the compilation according to the given `arguments`.

Returns:: zero (`0`) for success, non-zero (`!= 0`) for an error.

==== Arguments

The `arguments` specify the set of options, translation units to transform,
or transformed translation units to link into a program. An argument is either
an option and option value, or a name of a translation unit source. Options
start with the `{P}` or `{PP}` option prefix.

===== Long & Short Options

Arguments that start with `{PP}` are _long options_. And arguments that start
with a single `{P}` are _short options_. _Long options_ are expected to be
succinct but reasonably human readable names of options. And _short options_
are expected to be well know one or two character alternatives to the
_long options_.

===== Core Options

_Core options_ follow this syntax:

[subs="normal"]
....
{PP}__name__[=__value__]
{PP}__name__ [__value__]
{P}__n__ [__value__]
....

Where the _value_ for the option may be optional, and may have additional
syntax constraints, as specified for any particular option.

===== Vendor Options

_Vendor options_ are specified in a vendor specific _standing document_ and
follow the syntax of:

[subs="normal"]
....
{PP}__vendor-key__:__name__[=__value__]
{PP}__vendor-key__:__name__ [__value__]
{P}__vendor-key__:__n__ [__value__]
....

Where the _value_ for the option may be optional, and may have additional
syntax constraints, as specified for any particular option.

===== Compatibility

Options, and their values, can have a _compatibility_ of:

_Link incompatible_::
Wherein translation units transformed with differing options or values *can not*
be linked together into a program.

_Link compatible_::
Wherein translation units transformed with differing options or values *can*
be linked together into a program.

_Implementation defined_::
Wherein translation units transformed with differing options or values are
compatible depending on the particular C++ implementation.

_NA_::
Wherein the compatibility is not directly impacted by the option or values.

Options that are _link incompatible_ with other options also indicate which other
options affect compatibility. Otherwise a _link incompatible_ option is only
incompatible between its different values.

===== Options

include::../src/opt_core.cpp[leveloffset=+5,tag=std_cpp]

== Prior Art

=== `B2` build system

The `B2` (aka Boost Build) build system uses the concept of features to
portably abstract the declaration of compiler options to a portable
specification. For example:

* `optimization=off` would add the compiler specific option to turn off
  any code optimization.
* `debug-symbols=on` would add the compiler specific option to add source
  level debugging information to the output.
* `address-model=64` would add compiler specific options to generate
  64-bit addressing only code.

=== `clang-cl`

The Microsoft Visual Studio development environment supports using Clang
as an alternative compiler to their msvc (`cl.exe`) compiler. In order
to avoid reflecting the Clang specific options up into the IDE
Visual Studio implements a compiler front end that translates from
msvc options to Clang options (`clang-cl.exe`).

=== Cmake build system

Like the features of `b2` modern Cmake also implements a series of
variables that provide an abstraction to common compiler options.
For example:

* `set_property(TARGET foo PROPERTY CXX_STANDARD 11)` would add the compiler
  specific option to restrict compilation to use Standard C++11 features.

=== NVRTC

There is an existing example of providing an interface to the compiler:

****
link:https://docs.nvidia.com/cuda/nvrtc/index.html[NVRTC is a runtime
compilation library for CUDA{PP}]
****

It provides for a way to take CUDA specific {CPP} source (as data) and compile
it to produce a CUDA specific binary executable program. Although not as simple
of an interface as we are proposing in this extension it's very similar in
approach. Providing for the arguments to control the compile as `options`:

====
nvrtcResult nvrtcCompileProgram ( nvrtcProgram prog, int  numOptions, const char** options )
====

== Acknowledgements

Thanks to CppCon 2017 for providing the environment for "arguments" about
build systems, package managers, and dependency managers that created the
impetus for this idea.
